webProje(3.odev)/webProje(3.odev)/Controllers/RolYonetimController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using webProje_3.odev_.Models;

namespace webProje_3.odev_.Controllers
{
    [Authorize(Roles ="admin")]
    public class RolYonetimController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();

        // GET: RolYonetim
        public ActionResult RolGoster()
        {
          var rolstore=new  RoleStore<IdentityRole>(context);
            var rolManager = new RoleManager<IdentityRole>(rolstore);
          var goster=  rolManager.Roles.ToList();
            return View(goster);
        }
        public ActionResult RolKullaniciEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult RolKullaniciEkle(KullaniciRolEkle model)
        {
            var rolstore = new RoleStore<IdentityRole>(context);
            var rolManager = new RoleManager<IdentityRole>(rolstore);

            var userStore = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(userStore);
          var kullanici=  userManager.FindByName(model.KullaniciAdi);
            if (kullanici!=null)
            {
                if (!userManager.IsInRole(kullanici.Id, model.RolAdi))
                {
                    userManager.AddToRole(kullanici.Id, model.RolAdi);
                }
            }
            

            return RedirectToAction("RolGoster");
        }
    }
}

webProje(3.odev)/webProje(3.odev)/Views/RolYonetim/RolGoster.cshtml
@model List< Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "RolGoster";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>RolGoster</h2>
<ul>
    @foreach (var item in Model)
    {
        <li>@item.Name - @item.Users.Count</li>
    }
   
</ul>

@Html.ActionLink("Rol Ata", "RolKullaniciEkle", "RolYonetim")

webProje(3.odev)/webProje(3.odev)/Views/RolYonetim/RolKullaniciEkle.cshtml
@model webProje_3.odev_.Models.KullaniciRolEkle

@{
    ViewBag.Title = "RolKullaniciEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>RolKullaniciEkle</h2>

@using (Html.BeginForm("RolKullaniciEkle", "RolYonetim", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
{

    <div class="row">
        <div class="form-horizontal">

            <div class="form-group">
                <div class="col-md-12">
                    <label class="col-sm-2 control-label">Kullanıcı Adı</label>
                    <div class="col-sm-10">
                     
                        @Html.TextBoxFor(m => m.KullaniciAdi, new { @class = "form-control" })

                    </div>
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-12">
                    <label class="col-sm-2 control-label">Role Adı</label>
                    <div class="col-sm-10">

                        @Html.TextBoxFor(m => m.RolAdi, new { @class = "form-control" })

                    </div>
                </div>
            </div>
            <div class="panel-footer">
                <div class="row">
                    <div class="col-sm-9 col-sm-offset-3">
                        <div class="btn-toolbar pull-center">
                            <input type="submit" value="Kaydet" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
}